build:
	docker-compose -p chatapp build

up:
	docker-compose -p chatapp up -d

kill:
	docker-compose -p chatapp kill

rm:
	docker-compose -p chatapp rm -f

logs:
	docker-compose -p chatapp logs -f --tail=10

atom:
	GOPATH="../server/vendor/" atom ../
